### ISSUE TITLE
Orca error with Docker image - plotly.py unable to communicate with the local orca server process

### ISSUE THREAD

**Issue by FRB-JIM** [sonatype-nexus-community/iq-success-metrics#29]
1. Start Docker container (manually)
$ docker run --entrypoint /bin/bash --name iq-success-metrics --rm -it -v iq_metrics/data:/usr/src/app/output sonatypecommunity/iq-success-metrics:latest

root@ff91cdc1f730:/usr/src/app#  python3.8 ./success_metrics.py -k -u https://nexusiq.myhost.org -a svc-nexusiq:reallybadpass -s 7 -r
WARNING: Ignoring SSL Certificate Validation
/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py:997: InsecureRequestWarning: Unverified HTTPS request is being made to host 'nexusiq.stls.frb.org'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
Updating snapshot.json
saved to output/snapshot.json
Total number of apps with scan reports in IQ server (including onboarded and later deleted apps): 328
/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py:997: InsecureRequestWarning: Unverified HTTPS request is being made to host 'nexusiq.stls.frb.org'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
Progress: |██████████████████████████████████████████████████| 100.0% Complete
Generating 2020-08-24_successmetrics.json
saved to output/2020-08-24_successmetrics.json
Generating the Executive report
Traceback (most recent call last):---------------------------| 5.6% Complete
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 156, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 387, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.8/http/client.py", line 1240, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.8/http/client.py", line 1286, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.8/http/client.py", line 1235, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.8/http/client.py", line 1006, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.8/http/client.py", line 946, in send
    self.connect()
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 184, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 168, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f301b8d25b0>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 719, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=33932): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f301b8d25b0>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/plotly/io/_orca.py", line 1508, in to_image
    response = request_image_with_retrying(
  File "/usr/local/lib/python3.8/site-packages/retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "/usr/local/lib/python3.8/site-packages/retrying.py", line 212, in call
    raise attempt.get()
  File "/usr/local/lib/python3.8/site-packages/retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "/usr/local/lib/python3.8/site-packages/six.py", line 696, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "/usr/local/lib/python3.8/site-packages/plotly/io/_orca.py", line 1418, in request_image_with_retrying
    response = post(server_url + "/", data=json_str)
  File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=33932): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f301b8d25b0>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./reports.py", line 1017, in <module>
    main()
  File "./reports.py", line 1013, in main
    exec(report+"()")
  File "<string>", line 1, in <module>
  File "./reports.py", line 783, in executiveAll
    pdf = executive(apps, summary, 'summary')
  File "./reports.py", line 422, in executive
    make_chart(
  File "./reports.py", line 82, in make_chart
    fig.write_image(filename)
  File "/usr/local/lib/python3.8/site-packages/plotly/basedatatypes.py", line 2688, in write_image
    return pio.write_image(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/plotly/io/_orca.py", line 1704, in write_image
    img_data = to_image(
  File "/usr/local/lib/python3.8/site-packages/plotly/io/_orca.py", line 1520, in to_image
    raise ValueError(
ValueError:
For some reason plotly.py was unable to communicate with the
local orca server process, even though the server process seems to be running.

Please review the process and connection information below:

orca status
-----------
    state: running
    executable: /usr/bin/xvfb-run --auto-servernum --server-args -screen 0 640x480x24 +extension RANDR +extension GLX /usr/bin/orca
    version: 1.2.1
    port: 33932
    pid: 99
    command: ['/usr/bin/xvfb-run', '--auto-servernum', '--server-args', '-screen 0 640x480x24 +extension RANDR +extension GLX', '/usr/bin/orca', 'serve', '-p', '33932', '--plotly', '/usr/local/lib/python3.8/site-packages/plotly/package_data/plotly.min.js', '--graph-only', '--mathjax', 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js']

**Comment by FRB-JIM** [comment]
Trying to run the command manually:
root@020330db10a6:/usr/src/app# /usr/bin/xvfb-run --auto-servernum --server-args -screen 0 640x480x24 +extension RANDR +extension GLX /usr/bin/orca
/usr/bin/xvfb-run: 184: /usr/bin/xvfb-run: 0: not found

**Comment by cmorenoserrano** [comment]
Multiple customers are seeing this behaviour. However, it is working fine for me and my colleagues.
The script itself is not the problem, but a docker or network issue when the plotly library from the main container tries to communicate with the orca container.
Because it is not a script issue, we have very little influence in solving this problem.
However, we have an alternative for people experiencing this issue: we have a java Web App that should work seemlessly. [You can get it here](https://github.com/sonatype-nexus-community/iq-success-metrics2)
It comes with full instructions and everything you need to get your reports.
