### ISSUE TITLE
Error running script on Windows

### ISSUE THREAD

**Issue by rgmz** [sonatype-nexus-community/iq-success-metrics#30]
* **What are you trying to do?**

When running the Python script on Windows (we cannot use Docker), it will fail with the following error. It runs without issue on macOS.
```
Updating snapshot.json
saved to output/snapshot.json
Total number of apps with scan reports in IQ server (including onboarded and later deleted apps): 1234
Traceback (most recent call last):---------------------------| 0.0%% Complete
  File "success_metrics.py", line 811, in <module>
    main()
  File "success_metrics.py", line 547, in main
    runScript(args,appId,orgId,first,last,today)
  File "success_metrics.py", line 113, in runScript
    printProgressBar(t,segments)
  File "success_metrics.py", line 49, in printProgressBar
    print('\r{} |{}| {}%% {}'.format(prefix, bar, percent, suffix), end = '\r')
  File "C:\Users\<name>\AppData\Local\Programs\Python\Python38\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 12-15: character maps to <undefined>
```

If we comment out the line in question, the script will run without issue.
https://github.com/sonatype-nexus-community/iq-success-metrics/blob/b95f10c9ca0e0bc76bebc12b34e60a7281481e06/success_metrics.py#L49

* **How could we solve this issue? (Not knowing is okay!)**

I don't personally use a Windows machine so I cannot troubleshoot, however, it seems to be related to [UTF-8](https://medium.com/@kainingshao/unicodeencodeerror-charmap-codec-can-t-encode-characters-in-position-9-13-character-maps-to-be489944a34f#:~:text=1-,UnicodeEncodeError%3A%20'charmap'%20codec%20can't%20encode%20characters%20in,%3A%20character%20maps%20to&text=This%20means%20that%20the%20python,character%20to%20the%20console's%20encoding.&text=Then%20you%20will%20get%20this,but%20the%20outfile%20is%20byte.).

cc @DarthHater @bhamail

**Comment by cmorenoserrano** [comment]
This is the first time that I get this error.
The funny thing is that the error is in the progress bar function! (which is completely spurious).
This script has been run hundreds of times, maybe thousands, on Windows and Mac machines without this error popping up, so it might have to do with that cp1252.py library. I notice that you have Python 3.8 installed, whereas I run Python 3.7. Maybe there is an issue in that cp1252.py library, something has changed and the charmap codec is now different and maps to undefined.
I agree with you that it has to be the decoding to UTF-8 or related to it.

**Comment by cmorenoserrano** [comment]
I think I found the solution on the internet. It definitely has to do from the change in version from Python 3.7 to Python 3.8.

The solution is to force stdout and stderr to code in UTF-8.
I have updated the code of success_metrics.py and tested and it works for me, but it was already working for me, so I cannot test that it works. I also don't have a Windows machine.
Would you mind to add these 3 lines in your code and run it through the Windows machine to confirm that it fixes the problem? If so, I will commit the changes and get a new release out.

The three lines in question are:
```
import io
#---------------------------------
sys.stdout = io.TextIOWrapper(sys.stdout.detach(), encoding = 'utf-8')
sys.stderr = io.TextIOWrapper(sys.stderr.detach(), encoding = 'utf-8')
```



<img width="527" alt="Screenshot 2020-08-26 at 10 29 27" src="https://user-images.githubusercontent.com/50919218/91287310-77849400-e787-11ea-8db7-ac1d06963b60.png">
